version: 1

merge:
  trigger:
    branches: ["main"]
    branch_patterns: ["feature/.*"]

  ignore:
    labels: ["do not merge"]
  method: squash

  branch_method:
    develop: squash
    master: merge
    main: merge
  merge_method:
    - method: squash
      trigger:
        max_commits: 3
  options:
    squash:
      title: "pull_request_title"
      body: "empty_body"
  delete_after_merge: true
  allow_merge_with_no_checks: true

update:
  trigger:
    labels: ["Update Me"]
  ignore:
    labels: ["Do Not Update"]
  ignore_drafts: true