policy:
  approval:
  - updating test folder

approval_rules:
- name: updating test folder
  if:
    only_changed_files:
      paths:
        - "demo/test.txt"
        - "demo-two/test.txt"
  requires:
    count: 1
    users: ["approveman"]
